# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b4541468472930a1b5954ca90a642471234c4e2c9c3a14199fb7cd55340742cc9c5b33ff2074a45e30caeaf714e96bbd27313009bac3049f1fbf9560d5a00b2

test:
  secret_key_base: 9f968a7b4cde0e907e2a7039f4ddf6c6da118c36e5a39e370a8993a6b192b0306c039f2568ec0329dac42b55b27d5fd7dde7910c6a011854eb0b7e67086d635f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
